### ISSUE TITLE
Possible error on the ReadMe. OrderDownload

### ISSUE THREAD

**Issue by TriJoe** [khaoscontrol/kcc-web-services#30]
Under Config File > Structure > OrderDownload, it says under "URL", "The URL of the endpoint, where data is POSTed for you to process". This isn't correct. I am only seeing GET requests and the description is incorrect as it's the endpoint to which KhaosControl requests orders from the sales channel. 

It's possible the other descriptions are incorrect too.

**Comment by IThompsonKC** [comment]
Thank you for flagging this up. We will review these descriptions and update.

**Comment by IThompsonKC** [comment]
Descriptions have been modified to correctly state when they are making GET requests to the endpoints.
